<?php

/**
 * @OA\Schema(
 *   schema="Transaction",
 *   type="object",
 *   required={
 *     "id",
 *     "type",
 *     "amount",
 *     "currency",
 *     "collected_currency",
 *     "date",
 *     "ref_type",
 *     "ref_id",
 *     "expected_collecting_date",
 *     "merchant_id",
 *     "payment_system",
 *   },
 *   @OA\Property(
 *     property="id",
 *     type="integer",
 *   ),
 *   @OA\Property(
 *     property="type",
 *     type="string",
 *   ),
 *   @OA\Property(
 *     property="amount",
 *     type="string",
 *   ),
 *   @OA\Property(
 *     property="currency",
 *     type="string",
 *   ),
 *   @OA\Property(
 *     property="date",
 *     type="date",
 *   ),
 *   @OA\Property(
 *     property="ref_type",
 *     type="string",
 *   ),
 *   @OA\Property(
 *     property="ref_id",
 *     type="string",
 *   ),
 *   @OA\Property(
 *     property="expected_collecting_date",
 *     type="date",
 *   ),
 *   @OA\Property(
 *     property="merchant_id",
 *     type="string",
 *   ),
 *   @OA\Property(
 *     property="payment_system",
 *     type="string",
 *   ),
 * )
 */
